# Logistic Regression

Insert Library Needed

In [30]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import time
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

Insert Data

In [31]:
df = pd.read_csv('HDB_database_final.csv')
df.head()

town flat_type  floor_area_sqm  remaining_lease_months  resale_price  \
0  ANG MO KIO    3 ROOM            68.0                     714      274000.0   
1  ANG MO KIO    3 ROOM            68.0                     714      315000.0   
2  ANG MO KIO    3 ROOM            70.0                    1093      500000.0   
3  ANG MO KIO    3 ROOM            82.0                     713      315000.0   
4  ANG MO KIO    3 ROOM            67.0                     696      235000.0   

   distanceWithMrt  distanceWithRaffles  distanceWithGdPri  
0       881.003375          8703.096482        1041.995726  
1       985.490578          8617.203081        1048.316784  
2       689.479121          9113.711978        1199.433818  
3       881.003375          8703.096482        1041.995726  
4      1072.597799          8872.728560        1542.266971

Preprocess Data

In [32]:
def myfunction(x):
    if x <= 325000:
        return 0
    elif x <= 390000:
        return 1
    elif x <= 455000:
        return 2
    elif x <= 555000:
        return 3
    else:
        return 4

#apply function
df["resale_price"]=df["resale_price"].apply(myfunction)
df.head()

town flat_type  floor_area_sqm  remaining_lease_months  resale_price  \
0  ANG MO KIO    3 ROOM            68.0                     714             0   
1  ANG MO KIO    3 ROOM            68.0                     714             0   
2  ANG MO KIO    3 ROOM            70.0                    1093             3   
3  ANG MO KIO    3 ROOM            82.0                     713             0   
4  ANG MO KIO    3 ROOM            67.0                     696             0   

   distanceWithMrt  distanceWithRaffles  distanceWithGdPri  
0       881.003375          8703.096482        1041.995726  
1       985.490578          8617.203081        1048.316784  
2       689.479121          9113.711978        1199.433818  
3       881.003375          8703.096482        1041.995726  
4      1072.597799          8872.728560        1542.266971

In [33]:
print(len(df[df["resale_price"]==0]))
print(len(df[df["resale_price"]==1]))
print(len(df[df["resale_price"]==2]))
print(len(df[df["resale_price"]==3]))
print(len(df[df["resale_price"]==4]))

502
485
482
475
477


Model Training

In [45]:
def logisticReg(x,y):
    x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=0)
    
    logReg = LogisticRegression(solver = 'liblinear', random_state = 0, max_iter = 6000)
    logReg.fit(x_train, y_train)
    y_pred = logReg.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print('Accuracy: ' + str(accuracy))
    print(confusion_matrix(y_test, y_pred))
    

    return logReg

Model Validation

In [46]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithMrt","distanceWithRaffles","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logReg = logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

t3=time.time()
print('predict : ',logReg.predict([[67 ,881,1000 ,1000 ,714]]))
t4 = time.time()
t5 = t4-t3
print (f"predict time: {t5} s") # the time would be round to 3 decimal in seconds

Accuracy: 0.41254125412541254
[[78  5 29  3 20]
 [34 12 47 24 21]
 [20  3 41 33  8]
 [ 6  2 31 35 40]
 [ 6  2 13  9 84]]
training time: 0.02043318748474121 s
predict :  [4]
predict time: 0.0005159378051757812 s


# Best combination based on parameter test below

In [47]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logReg =  logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

t3=time.time()
print('predict : ',logReg.predict([[67 ,881 ,714]]))
t4 = time.time()
t5 = t4-t3
print (f"predict time: {t5} s") # the time would be round to 3 decimal in seconds

Accuracy: 0.466996699669967
[[122   2   6   4   1]
 [ 43  12  51  20  12]
 [  9   3  47  17  29]
 [  7   3  32  24  48]
 [  4   4  21   7  78]]
training time: 0.016858577728271484 s
predict :  [0]
predict time: 0.0010249614715576172 s


# Reduce 1 parameter

In [49]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithMrt","distanceWithRaffles","distanceWithGdPri"]]
y = df["resale_price"]
logReg =  logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

t3=time.time()
print('predict : ',logReg.predict([[67 ,881,1000 ,714]]))
t4 = time.time()
t5 = t4-t3
print (f"predict time: {t5} s") # the time would be round to 3 decimal in seconds

Accuracy: 0.3910891089108911
[[78  6 28  5 18]
 [35 10 48 24 21]
 [18  6 41 32  8]
 [ 4  2 34 31 43]
 [ 4  1 12 20 77]]
training time: 0.017841100692749023 s
predict :  [4]
predict time: 0.001018524169921875 s


In [196]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithMrt","distanceWithRaffles","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.3696369636963696
[[56  8 41  6 24]
 [33 12 48 24 21]
 [21  3 39 34  8]
 [17  0 26 29 42]
 [ 3  0 12 11 88]]
training time: 0.024083375930786133 s


In [197]:
#selected
t0=time.time()
x = df[["floor_area_sqm","distanceWithMrt","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.4537953795379538
[[123   1   9   1   1]
 [ 44   9  51  17  17]
 [  8   3  41  23  30]
 [  7   3  29  24  51]
 [  4   1  15  16  78]]
training time: 0.029084205627441406 s


In [198]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithRaffles","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.41089108910891087
[[82  4 25  2 22]
 [36 12 53 12 25]
 [18  4 53 17 13]
 [ 6  3 47 23 35]
 [ 5  3 18  9 79]]
training time: 0.024521827697753906 s


In [199]:
t0=time.time()
x = df[["distanceWithMrt","distanceWithRaffles","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.3085808580858086
[[40 13 42 12 28]
 [15 12 60 24 27]
 [16 10 40 27 12]
 [ 8  3 36 32 35]
 [14  4 22 11 63]]
training time: 0.01897120475769043 s


# Reduce 2 Parameters

In [50]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithMrt","distanceWithGdPri"]]
y = df["resale_price"]
logReg = logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")


t3=time.time()
print('predict : ',logReg.predict([[67 ,881,1000]]))
t4 = time.time()
t5 = t4-t3
print (f"predict time: {t5} s") # the time would be round to 3 decimal in second

Accuracy: 0.4471947194719472
[[120   5   6   2   2]
 [ 38  11  50  18  21]
 [  4  11  43  19  28]
 [  6   6  33  26  43]
 [  9   9  15  10  71]]
training time: 0.01642441749572754 s
predict :  [0]
predict time: 0.001018524169921875 s


In [201]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithMrt","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.4471947194719472
[[124   3   6   1   1]
 [ 48  11  49  11  19]
 [  8   4  48  10  35]
 [  7   4  34   7  62]
 [  4   1  16  12  81]]
training time: 0.025461435317993164 s


In [202]:
#selected
t0=time.time()
x = df[["floor_area_sqm","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.466996699669967
[[122   2   6   4   1]
 [ 43  12  51  20  12]
 [  9   3  47  17  29]
 [  7   3  32  24  48]
 [  4   4  21   7  78]]
training time: 0.025929689407348633 s


In [203]:
t0=time.time()
x = df[["distanceWithMrt","distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.38613861386138615
[[109   3  10   5   8]
 [ 54   5  43  10  26]
 [ 23   1  43  19  19]
 [ 25   3  27  23  36]
 [ 32   1  19   8  54]]
training time: 0.02589893341064453 s


# Reduce 3 Parameters (No further improvement)

In [51]:
t0=time.time()
x = df[["floor_area_sqm","distanceWithGdPri"]]
y = df["resale_price"]
logReg = logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

t3=time.time()
print('predict : ',logReg.predict([[67 ,881]]))
t4 = time.time()
t5 = t4-t3
print (f"predict time: {t5} s") # the time would be round to 3 decimal in second

Accuracy: 0.4372937293729373
[[119   5   7   3   1]
 [ 38  16  56  12  16]
 [  5  15  41  16  28]
 [  6   8  30  20  50]
 [  9  14   8  14  69]]
training time: 0.013503789901733398 s
predict :  [0]
predict time: 0.0005083084106445312 s


In [205]:
t0=time.time()
x = df[["floor_area_sqm","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.4521452145214521
[[124   3   5   2   1]
 [ 48  15  52  10  13]
 [  8   7  50   2  38]
 [  7   4  33   6  64]
 [  4   2  29   0  79]]
training time: 0.014960050582885742 s


In [206]:
t0=time.time()
x = df[["distanceWithGdPri","remaining_lease_months"]]
y = df["resale_price"]
logisticReg(x,y)
t1 = time.time()
t2 = t1-t0
print (f"training time: {t2} s")

Accuracy: 0.3415841584158416
[[113   1  12   1   8]
 [ 57   3  50   8  20]
 [ 24   1  51   3  26]
 [ 28   4  54   4  24]
 [ 32   3  40   3  36]]
training time: 0.013930797576904297 s


# Test with only 1 parameter

In [53]:
z = df[["floor_area_sqm","distanceWithMrt","distanceWithRaffles","distanceWithGdPri","remaining_lease_months"]]
for x in range(5):
    t0=time.time()
    x4 = z.iloc[:,x].to_frame()
    y4 = df["resale_price"]
    logisticReg(x4,y4)
    t1 = time.time()
    t2 = t1-t0
    print (f"training time: {t2} s")
    


Accuracy: 0.4438943894389439
[[123   4   6   0   2]
 [ 40  35  50   0  13]
 [  4  30  32   0  39]
 [  6  17  26   0  65]
 [  8  15  12   0  79]]
training time: 0.009680986404418945 s
Accuracy: 0.23102310231023102
[[19  0 54  1 61]
 [14  0 66  0 58]
 [13  0 60  0 32]
 [13  0 51  0 50]
 [19  0 32  2 61]]
training time: 0.020591020584106445 s
Accuracy: 0.17326732673267325
[[  0   0 135   0   0]
 [  0   0 138   0   0]
 [  0   0 105   0   0]
 [  0   0 114   0   0]
 [  0   0 114   0   0]]
training time: 0.008519649505615234 s
Accuracy: 0.2145214521452145
[[21  0 61  9 44]
 [18  0 79 13 28]
 [10  0 70  5 20]
 [14  0 77  9 14]
 [19  0 59  6 30]]
training time: 0.009657859802246094 s
Accuracy: 0.3250825082508251
[[113   1  21   0   0]
 [ 57   5  76   0   0]
 [ 25   1  79   0   0]
 [ 28   8  78   0   0]
 [ 32   7  75   0   0]]
training time: 0.008669376373291016 s
